services:
  oauth-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - "8080:8080"
    volumes:
      - ./hack/mock-oauth2-server.json:/app/config.json
    environment:
      JSON_CONFIG_PATH: /app/config.json
