---
apiVersion: nais.io/v1
kind: MaskinportenClient
metadata:
  name: texas-client
  namespace: nais-system
spec:
  scopes:
    consumes:
      - name: "nav:test/api"
  secretName: texas-client-maskinporten
---
apiVersion: nais.io/v1
kind: Jwker
metadata:
  name: texas-client
  namespace: nais-system
spec:
  accessPolicy:
    inbound:
      rules:
        - application: texas-client
  secretName: texas-client-tokenx
---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: texas-client
  namespace: nais-system
spec:
  allowAllUsers: true
  tenant: nav.no
  secretName: texas-client-entra
